on: [push]

jobs:
    build_new:
        name: Compile with GCC 7.5
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2.2.0
        - name: Copy scripts and src....
          run: ./scripts/setup_new_gcc.sh
        - name: Compile with gcc 7.5
          uses: ./.github/new_gcc_action/
        - name: Clean up of scripts and src files...
          run: ./scripts/cleanup.sh
    build_old:
        name: Compile with GCC 4.8
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2.2.0
        - name: Copy scripts and src....
          run: ./scripts/setup_old_gcc.sh
        - name: Compile with gcc 4.8
          uses: ./.github/old_gcc_action/
        - name: Clean up of scripts and src files...
          run: ./scripts/cleanup.sh
