on: [push]

jobs:
    build_new:
        name: Compile a build using gcc 7.5
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2.2.0
        - name: Compile 7.5
          uses: githubActionsPlayground/action.new@v1
    build_old:
        name: Compile a build using gcc 4.8
        runs-on: ubuntu-latest
        steps:
        - name: Compile 4.8
          uses: githubActionsPlayground/action.old@v1
